name: armTemplateDeployment
on: 
  workflow_dispatch:

jobs:
  armDeploySandbox:
    name: Deploy to Sandbox
    runs-on: ubuntu-latest
    env:
      subscriptionId: 0929d555-466f-4f2b-9354-a455f36b9732
      resource_group_name: Customer-Int001-RG-Sandbox
      location: Australia East
    environment:
      name: Sandbox

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Deploy Resource Group ${{env.resource_group_name}}
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{env.subscriptionId}}
          region: ${{env.location}} 
          template: ./arm-templates/resourcegroup.json
          deploymentName: ${{env.resource_group_name}}
          parameters:
            resourceGroupName=${{env.resource_group_name}}
         
      - name: Create Logic App
        uses: azure/bicep-deploy@v1
        with:
          type: deployment
          operation: create
          name: Development
          scope: resourceGroup
          subscription-id: ${{env.subscriptionId}}
          resource-group-name: ${{env.resource_group_name}}
          template-file: ./arm-templates/logicapp1.json

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{env.resource_group_name}}
          subscriptionId: ${{env.subscriptionId}}
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storageaccount.parameters.json
          deploymentMode: incremental
          
  armDeployProduction:
      name: Deploy to Production
      runs-on: ubuntu-latest
      env:
        subscriptionId: 2e3ff3b2-094d-4496-9ed2-5d98f43e21b1
        resource_group_name: Customer-Int001-RG-Prod
        location: Australia East
      environment:
        name: Production
      
      needs: armDeploySandbox  

      steps:
        - uses: actions/checkout@v2

        - name: Azure Login
          uses: Azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        
        - name: Deploy Resource Group "rg-githubaction"
          uses: Azure/arm-deploy@v2
          with:
            scope: subscription
            subscriptionId: ${{env.subscriptionId}}
            region: Australia East
            template: ./arm-templates/resourcegroup.json
            deploymentName: ${{env.resource_group_name}}

        - name: Create Logic App
          uses: azure/bicep-deploy@v1
          with:
            type: deployment
            operation: create
            name: Development
            scope: resourceGroup
            subscription-id: ${{env.subscriptionId}}
            resource-group-name: ${{env.resource_group_name}}
            template-file: ./arm-templates/logicapp1.json
            
        - name: Deploy Storage Account
          uses: Azure/arm-deploy@v2
          id: storageAccountDeploy
          with:
            scope: resourcegroup
            resourceGroupName: ${{env.resource_group_name}}
            subscriptionId: ${{env.subscriptionId}}
            template: ./arm-templates/storageaccount.json
            parameters: 
              sku=Standard_LRS
              storageAccountName=nonoodlesstg002
              location="Australia Central"
            deploymentMode: incremental
