name: armTemplateDeployment
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Deploy Resource Group "rg-githubaction"
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: 2e3ff3b2-094d-4496-9ed2-5d98f43e21b1
          region: Australia East
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions
          
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 2e3ff3b2-094d-4496-9ed2-5d98f43e21b1
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storageaccount.parameters.json
          deploymentMode: incremental
      
